### ISSUE TITLE
!warns and !dmwarns

### ISSUE THREAD

**Issue by BeagleJonas** [Blackcatmaxy/Botcatmaxy#124]
**Describe the bug**
The !warns command in  servers only works if you have the ban permission, and allows you to check other users' infractions. The  !dmwarns command however does not require any permission and also allows you to check other users' infractions.

**Expected behavior**
!dmwarns won't check other user's infractions unless you have the proper permission to do so.

**Comment by Blackcatmaxy** [comment]
Well there's multiple misconceptions to clear up here, but every single assumption in this issue is wrong.
Let's start with the main misconception and why this isn't a bug. The creation of `!dmwarns` was to lower the amount of flood in channels so that people could see all of their infractions without filling up someone else's screen. Even in a bot channel, two people simultaneously checking someone's 60 infractions would be a bad scenario. But no one has ever presented a convincing reason for why you should not be able to see someone else infractions to me. It seems like basic accountability to have infractions public to all.

Eventually the `!warns` was restricted to those who had access to warn (people with kick permission or whitelisted roles), but if you try to use `!warns` in a server it will simply tell you that the command has been MOVED to the DM's suggesting that the command used in DM's is just as capable as the one in the server.
